# Generated by Django 5.0.7 on 2024-07-18 23:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Hospede',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_quarto', models.CharField(max_length=10, unique=True)),
                ('tipo_quarto', models.CharField(max_length=50)),
                ('preco_por_noite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('disponível', 'Disponível'), ('ocupado', 'Ocupado'), ('em manutenção', 'Em Manutenção')], default='disponível', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_check_in', models.DateTimeField()),
                ('data_check_out', models.DateTimeField()),
                ('status_reserva', models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], default='confirmada', max_length=20)),
                ('data_reserva', models.DateTimeField(default=django.utils.timezone.now)),
                ('hospede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='polls.hospede')),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='polls.quarto')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
